Update DispatchServer.java
Melledy/Grasscutter pull request #105
Opened 2022-04-22 05:33 UTC by Scirese

Add Android Client fix by @BaiSugar
Fix #76

2022-04-22 07:30 UTC, MlgmXyysd commented
More information is required. I noticed that Android client can enter normally without this patch.

2022-04-22 07:51 UTC, Scirese commented
> More information is required. I noticed that Android client can enter normally without this patch.

If without this patch ,android client will behave the same as #76 .
Im using stable 1.0.0 to test,which is not included this patch.

2022-04-23 05:39 UTC, Scirese commented
new dev has fixed the issue. closing this pr.

2022-04-24 14:24 UTC, Scirese commented
The issue still needs attention !!!
If without this patch,some android client will behave the same as #76  。

2022-04-26 11:30 UTC, xi-lu commented
#150

2022-04-26 23:22 UTC, memetrollsXD approved these changes
Looks good, and doesn't change anything auth wise

2022-04-27 17:07 UTC, PinkD requested changes

2022-04-27 17:07 UTC, PinkD commented on src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java
> +				new DispatchHttpJsonHandler("{\"retcode\":0,\"message\":\"OK\",\"data\":{\"id\":\"none\",\"action\":\"ACTION_NONE\",\"geetest\":null}}") );
```suggestion
				new DispatchHttpJsonHandler("{\"retcode\":0,\"message\":\"OK\",\"data\":{\"id\":\"none\",\"action\":\"ACTION_NONE\",\"geetest\":null}}")
```

2022-04-29 20:32 UTC, memetrollsXD commented
If this still requires attention, please fix the merge conflicts. If not, I'll close the PR.

2022-04-30 02:33 UTC, Scirese commented
> If this still requires attention, please fix the merge conflicts. If not, I'll close the PR

conflicts are resolved.

2022-04-30 09:45 UTC, merged