Fix unable to save game data occasionally
Melledy/Grasscutter pull request #1194
Opened 2022-06-04 14:45 UTC by zhaodice

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My pull request is unique and no other pull requests have been opened for these changes
- [ ] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [ ] I am responsible for any copyright issues with my code if it occurs in the future.

2022-06-04 17:41 UTC, zhaodice commented
I am sorry but too many problem with this project, I can't edit simply, if you have any question ,fell free to ask me

2022-06-05 06:18 UTC, zhaodice commented
All done, I have tested it would be very stable

2022-06-05 06:23 UTC, zhaodice commented
Note : `7b07ad6` was delect by `e2db401`

2022-06-05 07:16 UTC, Melledy requested changes

2022-06-05 07:16 UTC, Melledy commented on src/main/java/emu/grasscutter/server/game/GameServerInitializer.java
> +        new GameSession(server,ch.pipeline());
Please keep the existing code as is, in case a session needs to be created without a pipeline.

2022-06-05 07:16 UTC, Melledy commented on src/main/java/emu/grasscutter/server/packet/recv/HandlerGetPlayerTokenReq.java
> -		Account account = DatabaseHelper.getAccountById(req.getAccountUid());
Please keep the previous code here OR do an account id check just in case.

2022-06-05 08:09 UTC, zhaodice commented
All done.

2022-06-05 10:07 UTC, AZthemute commented
> If there are 5 online players, max count of player is 5,
> a new client want to login by kicking one of them ,
> I think it should be allowed

As an option we can easily toggle?

2022-06-05 10:19 UTC, zhaodice commented
> > If there are 5 online players, max count of player is 5,
> > a new client want to login by kicking one of them ,
> > I think it should be allowed
> 
> As an option we can easily toggle?

you mean you want a switch that when no available position, could decline new client's login request although the client has one of their account?

2022-06-05 10:28 UTC, zhaodice commented
> As an option we can easily toggle?

If there are 5 online players, max count of player is 5,
a new client **( who has one of their account)** want to login by kicking one of them ,
I think it should be allowed

2022-06-05 11:23 UTC, Melledy approved these changes

2022-06-05 11:23 UTC, merged