fix healing ability of some characters to some extent
Melledy/Grasscutter pull request #1201
Opened 2022-06-05 15:38 UTC by saucebing

## Description

fix healing ability of some characters to some extent

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2022-06-05 16:04 UTC, zhaodice commented
see #1202

2022-06-05 16:11 UTC, Akka0 commented on src/main/java/emu/grasscutter/data/ResourceLoader.java
> +                lines = lines.replaceAll("HNEIEGHMLKH", "modifiers");
It's recommended to use like `@SerializedName(value="x", alternate={"_x", "X"})` in data class instead, see `Position` class

2022-06-06 00:32 UTC, Melledy approved these changes

2022-06-06 00:32 UTC, Melledy commented on src/main/java/emu/grasscutter/game/ability/AbilityManager.java
> +                ArrayList<HealData> healDataList = new ArrayList();
While this is a step in the right direction, variables from HealData are dynamic and recieved from the client so there is no need to hard code every character's healing amount.

2022-06-06 00:37 UTC, Melledy requested changes
Didn't mean to approve, my mistake. Please resolve mine and @Akka0's requested changes first.

2022-06-06 01:41 UTC, saucebing commented
I have resolved @Akka0 's requested changes. As for @Melledy 's, maybe I need to sniff. However, it need some time. I will be appreciated if anyone can help me or provide some guidance.

2022-06-06 23:50 UTC, Melledy commented
> I have resolved @Akka0 's requested changes. As for @Melledy 's, maybe I need to sniff. However, it need some time. I will be appreciated if anyone can help me or provide some guidance.

The client sends ability variables and their values to the server, which are handled and stored in `entity::getMetaOverrideMap()`

2022-06-07 09:02 UTC, saucebing commented
> > I have resolved @Akka0 's requested changes. As for @Melledy 's, maybe I need to sniff. However, it need some time. I will be appreciated if anyone can help me or provide some guidance.
> 
> The client sends ability variables and their values to the server, which are handled and stored in `entity::getMetaOverrideMap()`

Thank you for your guidances, Melledy. In invokeAction function, I tried to check keys and values in entity::getMetaOverrideMap(), and found that it did store the healing base and percentage of some skills, such as E skills of Kokomi and Qiqi. However, it still lacks of some other skills, such as Q skill of Qiqi, in which there is nothing in entity::getMetaOverrideMap(). Do you know the possible reason? Or do you have any suggestion?

2022-06-10 06:25 UTC, zhaodice commented
> Thank you for your guidances, Melledy. In invokeAction function, I tried to check keys and values in entity::getMetaOverrideMap(), and found that it did store the healing base and percentage of some skills, such as E skills of Kokomi and Qiqi. However, it still lacks of some other skills, such as Q skill of Qiqi, in which there is nothing in entity::getMetaOverrideMap(). Do you know the possible reason? Or do you have any suggestion?

May you could supply information about Q of Qiqi to it?

2022-06-10 06:38 UTC, saucebing commented
> > Thank you for your guidances, Melledy. In invokeAction function, I tried to check keys and values in entity::getMetaOverrideMap(), and found that it did store the healing base and percentage of some skills, such as E skills of Kokomi and Qiqi. However, it still lacks of some other skills, such as Q skill of Qiqi, in which there is nothing in entity::getMetaOverrideMap(). Do you know the possible reason? Or do you have any suggestion?
> 
> Could you supply information about Q of Qiqi to getMetaOverrideMap?

I am trying, or I will use some other methods to try to solve it.

2022-06-13 15:28 UTC, saucebing commented
I have resolved @Melledy 's requested changes.
Now I have fixed:
(1) E skills of Kokomi, Noel, Barbara, Shinobu and Qiqi; 
(2) Q skills of Qin, Bernett, Diona and Sayu.

2022-06-14 11:36 UTC, Melledy approved these changes

2022-06-14 11:36 UTC, merged

2022-06-14 16:36 UTC, Cardgodk commented
> 我已解决 @Melledy 请求的更改。现在我已经修复了：（1）Kokomi，Noel，Barbara，Shinobu和Qiqi的E技能; （2）秦、伯内特、迪奥娜、萨尤的Q技能。

Hello, I found a small problem. Kokomi's e skill recovery value should benefit from Kokomi's own HP, not the maximum HP of the character she treats

2022-06-14 16:37 UTC, Cardgodk commented
> 

Because I haven't done a lot of testing, I'm not sure if Kokomi is the only one with this problem

2022-06-14 16:45 UTC, saucebing commented
> > 我已解决 @Melledy 请求的更改。现在我已经修复了：（1）Kokomi，Noel，Barbara，Shinobu和Qiqi的E技能; （2）秦、伯内特、迪奥娜、萨尤的Q技能。
> 
> Hello, I found a small problem. Kokomi's e skill recovery value should benefit from Kokomi's own HP, not the maximum HP of the character she treats

I have found this problem, which will be solved in the next pr.

2022-06-15 11:56 UTC, saucebing commented
> Kokomi's e skill recovery value should benefit from Kokomi's own HP, not the maximum HP of the character she treats

It is fixed in the latest pr.