Use count for level for equips (dev branch)
Melledy/Grasscutter pull request #128
Opened 2022-04-22 21:23 UTC by memetrollsXD

Leveling up weapons is a pain in the ass. Instead of going through all of that pain, I've brought you a simple solution:

If the weapon is a weapon or artifact, use the count as level. For example:

- `!give 13501 90` will give you a lvl. 90 Staff of Homa

2022-04-22 21:35 UTC, ghost requested changes
Weapons still have their ascension level (promoteLevel) that needs to be set accordingly when creating them at high levels. In addition, relics should be available to be created in bulk since they all have random stats. I recommend handling a 3rd argument for quantity.

2022-04-23 20:23 UTC, KingRainbow44 approved these changes

2022-04-23 20:24 UTC, KingRainbow44 approved these changes

2022-04-23 22:13 UTC, Melledy approved these changes

2022-04-23 22:15 UTC, merged