persist energyUsage and fix some issue.
Melledy/Grasscutter pull request #1291
Opened 2022-06-17 08:39 UTC by liizfq

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My pull request is unique and no other pull requests have been opened for these changes
- [ ] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [ ] I am responsible for any copyright issues with my code if it occurs in the future.

2022-06-17 10:50 UTC, kyoko12 requested changes

2022-06-17 10:50 UTC, kyoko12 commented on src/main/java/emu/grasscutter/game/avatar/Avatar.java
> +		if (this.getPlayer().getEnergyUsage()) {
This sets the energy irrespective of whether energy usage is turned on or off. That seems like a bug?

2022-06-17 10:50 UTC, kyoko12 commented on src/main/java/emu/grasscutter/game/entity/EntityAvatar.java
> +	}
It is confusing that there is now a `setCurrentEnergy` for both `Avatar` and `EntityAvatar`. Please unify them and put them into either one of those classes, probably in `EntityAvatar`.

2022-06-17 10:50 UTC, kyoko12 commented on src/main/java/emu/grasscutter/game/managers/energy/EnergyManager.java
> +        }
What is that? A fix for Favonius? Please put a discriptive comment if you handle a specific special case.

2022-06-17 10:50 UTC, kyoko12 commented on src/main/java/emu/grasscutter/utils/ConfigContainer.java
> +//        public boolean energyUsage = false;
I don't get what the point or benefit of this change is supposed to be. On the contrary, I can only see this as a detriment. What does taking away server manager's ability to set a default for whether they want to use such a - highly experimental, by the way - feature improve?

Giving the ability to override this config with a command is fine. Persisting that is fine too (though you would have to devise a way to differentiate between nothing being set and the feature being turned off). But taking away the configurability is not fine.

2022-06-17 10:50 UTC, kyoko12 commented on src/main/java/emu/grasscutter/game/avatar/Avatar.java
> +//	}
Leftover.

2022-06-17 10:50 UTC, kyoko12 commented on src/main/java/emu/grasscutter/game/entity/EntityAvatar.java
> +		setCurrentEnergy(curEnergyProp,curEnergy,reason);
This violates the protocol. On avatar creation, when this is called by the constructor, the live server sends neither an `AvatarFightPropUpdateNotify` nor an `EntityFightPropChangeReasonNotify`.

2022-06-18 23:22 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/entity/EntityAvatar.java
> +			this.getScene().broadcastPacket(new PacketEntityFightPropUpdateNotify(this, curEnergyProp));
Adding energy should send `AvatarFightPropUpdateNotify`.

2022-06-19 02:21 UTC, liizfq commented on src/main/java/emu/grasscutter/game/entity/EntityAvatar.java
> +			this.getScene().broadcastPacket(new PacketEntityFightPropUpdateNotify(this, curEnergyProp));
ok,but why send AvatarFightPropUpdateNotify before setCurrentEnergy?

2022-06-19 02:27 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/entity/EntityAvatar.java
> +			this.getScene().broadcastPacket(new PacketEntityFightPropUpdateNotify(this, curEnergyProp));
What do you mean?

2022-06-19 02:27 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/entity/EntityAvatar.java
> +			this.getScene().broadcastPacket(new PacketEntityFightPropUpdateNotify(this, curEnergyProp));
What do you mean?

2022-06-19 02:40 UTC, liizfq commented on src/main/java/emu/grasscutter/game/entity/EntityAvatar.java
> +			this.getScene().broadcastPacket(new PacketEntityFightPropUpdateNotify(this, curEnergyProp));
i guess that this.avatar.setCurrentEnergy(newEnergy)  executes before AvatarFightPropUpdateNotify.
AvatarFightPropUpdateNotify should notify the newEnergy.

2022-06-19 02:43 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/entity/EntityAvatar.java
> +			this.getScene().broadcastPacket(new PacketEntityFightPropUpdateNotify(this, curEnergyProp));
> i guess that this.avatar.setCurrentEnergy(newEnergy) executes before AvatarFightPropUpdateNotify.

Correct.

> AvatarFightPropUpdateNotify should notify the newEnergy.

Also correct.

I know it's slightly confusing, but there is a difference in how the official server handles communicating energy changes between adding and clearing energy. For adding energy, it sends `AvatarFightPropUpdateNotify`, and for clearing it sends `EntityFightPropUpdateNotify `

2022-06-28 05:31 UTC, closed without merging

2022-06-28 13:53 UTC, 1-lavender-1 commented
Why is this PR closed？I consider these new features are quite useful

2022-06-28 16:04 UTC, liizfq commented
> Why is this PR closed？I consider these new features are quite useful

i tried to fix conflict,but i failed.So i plan fork the lasted repository and add the new features.thanks for your reply.