Added more server debug options
Melledy/Grasscutter pull request #1444
Opened 2022-07-05 15:55 UTC by akatatsu27

## Description
In config.json on "debugLevel" you can now also input "WHITELIST" or "BLACKLIST".
The console will display or blacklist any packets (including those excluded by ALL: PingReq, PingRsp, WorldPlayerRTTNotify, UnionCmdNotify and QueryPathReq) whose opcodes are in the new fields "serverDebugWhitelist", and "serverDebugBlacklist" respectively. Did not touch the version number in ConfigContainer.java
## Issues fixed by this PR
## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x ] Enhancement
- [ ] Documentation

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] My pull request is unique and no other pull requests have been opened for these changes
- [ x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x ] I am responsible for any copyright issues with my code if it occurs in the future.

2022-07-05 20:04 UTC, GanyusLeftHorn requested changes

2022-07-05 20:04 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/server/game/GameSession.java
> +    			if (packet.getOpcode() == SERVER.serverDebugWhitelist[i]) {
This is way more complicated than it has to be. For example, if you store your white- and blacklist as lists instead of arrays, this simply becomes
```java
if (SERVER.debugLevel == ServerDebugMode.WHITELIST && SERVER.serverDebugWhitelist.contains(opcode)) {
```

2022-07-05 20:04 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/server/game/GameSession.java
> +				}
The logging code here is pretty much identical to the one in `send`. We should probably factor that out into a separate method and just call that in both `send` and  `handleReceive`.

2022-07-05 20:04 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/server/game/GameSession.java
> +     		if (!beBlacklisted) {
Likewise, this would become something like

```java
if (SERVER.debugLevel == ServerDebugMode.BLACKLIST && !SERVER.serverDebugBlacklist.contains(opcode)) {
```

2022-07-05 20:06 UTC, GanyusLeftHorn commented
I don't know how necessary adding both a whitelist and blacklist functionality is. I have definitely wanted the ability to log _everything_, including things like `UnionCmd`, before, so this added functionality is appreciated (at least for me personally). But whether we actually need both, I don't know.

2022-07-06 05:58 UTC, Melledy requested changes

2022-07-06 05:58 UTC, Melledy commented on src/main/java/emu/grasscutter/server/game/GameSession.java
> +    			if (packet.getOpcode() == SERVER.serverDebugWhitelist[i]) {
They should be stored as hashsets, not arrays.

2022-07-06 05:58 UTC, Melledy commented on src/main/java/emu/grasscutter/utils/ConfigContainer.java
> +        public int[] serverDebugWhitelist = {};
No need to append "server" in front of the config variable name.

2022-07-07 07:33 UTC, Melledy approved these changes

2022-07-08 17:31 UTC, merged