Create ro-RO.json
Melledy/Grasscutter pull request #1451
Opened 2022-07-06 21:07 UTC by haxxorer

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My pull request is unique and no other pull requests have been opened for these changes
- [ ] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [ ] I am responsible for any copyright issues with my code if it occurs in the future.

2022-07-06 21:09 UTC, Arikatsu reviewed
pog

2022-07-06 23:08 UTC, Secretboy-SMR commented
;

2022-07-07 07:10 UTC, Birdulon requested changes

2022-07-07 07:10 UTC, Birdulon commented on src/main/resources/languages/ro-RO.json
> +   Preview
```suggestion

```

2022-07-07 07:10 UTC, Birdulon commented on src/main/resources/languages/ro-RO.json
> +      "header_scene": "Scenă";
```suggestion
      "header_scene": "Scenă",
```

2022-07-07 07:13 UTC, Birdulon approved these changes

2022-07-07 07:13 UTC, merged