Fully Implement OpenState system
Melledy/Grasscutter pull request #1479
Opened 2022-07-09 20:22 UTC by akatatsu27

## Description

- Fully implements the OpenState. 
- On new Player creation closely mimics current official server -  client conversation.
- Correctly sends/handles packets: SetOpenStateChangeNotify, OpenStateUpdateNotify, SetOpenStateReq, SetOpenStateRsp
- On second login sets all OpenStates
- 
## Issues fixed by this PR

## Type of changes
- [ ] Bug fix
- [x ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] My pull request is unique and no other pull requests have been opened for these changes
- [x ] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x ] I am responsible for any copyright issues with my code if it occurs in the future.

2022-07-09 21:58 UTC, GanyusLeftHorn requested changes

2022-07-09 21:58 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/player/PlayerOpenStateManager.java
> +        return this.openStateMap.get(openState);
1) This will never work - `openStateMap` is a `Map<Integer, Integer>`, but this code uses `OpenState` as key to both check for existance as well as fetching the value, but crucially not for insertion. TL/DR: This method always returns `null`. Which you won't notice, since it is never called anyway.
1) The `if` here is unnecessary - `putIfAbsent` only writes the value if it is not already in the map. 
1) That being said, I don't think it is even necessary to insert the state into the map if it is missing. Simply use 
```
return this.openStateMap.getOrDefault(openState.getValue(), 0);
```

2022-07-09 21:58 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/player/PlayerOpenStateManager.java
> +        }
This is equivalent to 
```
this.openStateMap.put(openState.getValue(), value);
```

2022-07-09 21:58 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/player/PlayerOpenStateManager.java
> +        player.getSession().send(new PacketOpenStateChangeNotify(openState.getValue(),value));
Don't send a packet on every call to this method. Only send it if the value actually _changed_. Sending it every time leads to the player being barraged with unlock notifications on every login (starting from the second, but more on that later).

2022-07-09 21:58 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/player/PlayerOpenStateManager.java
> +    }
This overload seems unnecessary. `setOpenState(OpenState, Integer)` should be enough.

2022-07-09 21:58 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/player/PlayerOpenStateManager.java
> +    }
Those two methods are essentially equivalent (and have misleading names - both of them set both key and value). One of them should be enough.

2022-07-09 21:58 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/player/PlayerOpenStateManager.java
> +
This should probably be a static member of the class.

2022-07-09 21:58 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/player/PlayerOpenStateManager.java
> +        setOpenStatesByKey(openStatesChanged);
Shorter:
```
newPlayerOpenStates.forEach(os -> this.setOpenState(os, 1));
```

2022-07-09 21:58 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/player/PlayerOpenStateManager.java
> +        player.getSession().send(new PacketOpenStateUpdateNotify(player));
This is where I get really confused. Why set all OpenStates to 1 starting from the second login? Why even track them in the database at all then? Our current behavior is to set all OpenStates to 1 for _every_ login. Doing it for every login starting from the second is a marginal difference (which only leads to inconvenience for the player, with various systems like crafting or wishing only accessible starting from the second login).

This defeats the whole purpose of actually tracking OpenStates (which is a good thing that we definitely want to do in the long run, don't get me wrong). The correct thing to do would be to 
1) On _every_ login, return exactly the OpenStates stored in the database.
1) Implement all the ways in which OpenStates can get set (crucially including quest triggers).

Unfortunately, given that quests are not fully functional yet, this is probably going to be a problem. I would therefore suggest turning this PR into more of an infrastructure thing: Add OpenState tracking to the database, expose an interface for getting and setting them, _but_ be very generous with which OpenStates we set right off the bat (read: set all of them, as we currently do, or at least almost all of them). We can then gradually reduce the list of automatically set OpenStates when we add handling for the methods in which they are actually set.

2022-07-09 21:58 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/player/PlayerOpenStateManager.java
> +        setOpenStatesByKeyValue(openStatesChanged);
```
Stream.of(OpenState.values()).forEach(os -> this.setOpenState(os, 1));
```

2022-07-10 00:25 UTC, akatatsu27 commented on src/main/java/emu/grasscutter/game/player/PlayerOpenStateManager.java
> +        player.getSession().send(new PacketOpenStateUpdateNotify(player));
I was comparing with official server conversation with a new Player, and during the first quest, the client sends some SetOpenStateReq packets. I think its crucial we try to mimic the official server conversation to get stuff working. I've changed it to always set all OpenStates, but I'll leave the original onNewPlayerCreate commented out, for anyone who wants to experiment with new Player initial conditions

2022-07-10 10:39 UTC, closed without merging