Fix self-damage ability for E skill of Hu Tao
Melledy/Grasscutter pull request #1505
Opened 2022-07-13 07:05 UTC by Paimon2022

## Description

Fix self-damage ability for E skill of Hu Tao. Now she will consume 30% of the current HP.

## Issues fixed by this PR

## Type of changes

- [x] Bug fix
- [x] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2022-07-13 13:12 UTC, bfiics approved these changes

2022-07-19 23:30 UTC, KingRainbow44 requested changes

2022-07-19 23:30 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/game/ability/HSDAbilityManager.java
> +                        if(healDataAvatar.avatarName.equals("Hutao") && skillId == 10462) {
instead of hardcoding a system for *specifically* Hu Tao, consider adding a *system* for this

2022-07-19 23:30 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/packet/recv/HandlerEvtDoSkillSuccNotify.java
> +        HSDAbilityManager.skillId = skillId;
a static property here would not work in the long run, pass the ID through to the managers.

2022-07-26 16:11 UTC, KingRainbow44 commented
will be closing this PR as there are existing plans/developments to implement skills in a manager/system-style way.

2022-07-26 16:11 UTC, closed without merging