Read Open States from Excels
Melledy/Grasscutter pull request #1557
Opened 2022-07-23 23:29 UTC by GanyusLeftHorn

## Description

This PR removes the hardcoded `OpenState.java` and instead reads them from `OpenStateConfigData.json`. It also makes some refactorings for `PlayerOpenStateManager` and adds subcommands to `/setprop`:

- Open states are now read from `OpenStateConfigData.json`, including information on how they are unlocked.
- The set of open states that are unlocked on every account by default now comprises:
    * All states that are unlocked by default according to the config (`defaultState = true`).
    * `OPEN_STATE_PAIMON` (1), which we need to unlock to give the player access to a functioning chat for commands.
    * All states that have unlock conditions that we don't handle yet (quests, parent quests, reputation level etc.). This could (and should) be changed to NOT include states which are set by the client (`allowClientOpen = true`), however, there is a problem when the client shows UI hints and forces the player to click on UI icons that don't yet work correctly. In such a case, the hint on screen will never disappear. We could solve this by hardcoding the necessary states, like `OPEN_STATE_PAIMON` (or by making all the necessary UI buttons work ...).
    * NOT any of the states listed in `BLACKLIST_OPEN_STATES`. This is currently used for the border around the world map. As this is a quest-unlocked state (using some high-id dummy quest), this can be removed as soon as quest unlocks are fully implemented.
- The `/setprop` command was extended to allow temporarily setting and unsetting of open states for development and testing perposes. `/setprop setopenstate X` sets open state X, and `/setprop unsetopenstate X` removes the state. This is not saved to the DB, so the effects of this are purely temporary.

## Issues fixed by this PR

Fixes #1535 

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2022-07-23 23:44 UTC, Melledy requested changes

2022-07-23 23:44 UTC, Melledy commented on src/main/java/emu/grasscutter/data/excels/OpenStateData.java
> +        @Getter private String condType;
`condType` should be an enum instead of String. Gson automatically parses them to an enum.

2022-07-24 01:10 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/data/excels/OpenStateData.java
> +        @Getter private String condType;
Changed.

2022-07-24 07:11 UTC, Melledy approved these changes

2022-07-24 07:12 UTC, merged