Optimize logic and refactor code
Melledy/Grasscutter pull request #1707
Opened 2022-08-25 14:40 UTC by jianxingxuejian

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2022-08-25 23:52 UTC, Gmskjunior commented
Exit

Em qui., 25 de ago. de 2022 11:41, null ***@***.***> escreveu:

> Description
>
> Please carefully read the Contributing note
> <https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md>
> and Code of conduct
> <https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md>
> before making any pull requests.
> And, *Do not make a pull request to merge into stable unless it is a
> hotfix. Use the development branch instead.*
> Issues fixed by this PR Type of changes
>
>    - Bug fix
>    - New feature
>    - Enhancement
>    - Documentation
>
> Checklist:
>
>    - My code follows the style guidelines of this project
>    - My pull request is unique and no other pull requests have been
>    opened for these changes
>    - I have read the Contributing note
>    <https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md>
>    and Code of conduct
>    <https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md>
>    - I am responsible for any copyright issues with my code if it occurs
>    in the future.
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Grasscutters/Grasscutter/pull/1707
> Commit Summary
>
>    - 6f6ebf9
>    <https://github.com/Grasscutters/Grasscutter/pull/1707/commits/6f6ebf97f5969d37a872ae660165680b0da1dc02>
>    Optimize logic and refactor code
>
> File Changes
>
> (1 file <https://github.com/Grasscutters/Grasscutter/pull/1707/files>)
>
>    - *M* src/main/java/emu/grasscutter/auth/DefaultAuthenticators.java
>    <https://github.com/Grasscutters/Grasscutter/pull/1707/files#diff-6a0ebf50baafbc7c924aa5514ccfda20db75abbe92e7899482b25ad3fe8ef404>
>    (322)
>
> Patch Links:
>
>    - https://github.com/Grasscutters/Grasscutter/pull/1707.patch
>    - https://github.com/Grasscutters/Grasscutter/pull/1707.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Grasscutters/Grasscutter/pull/1707>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2ME6AR6AXXIK5XQJWODGC3V26AYJANCNFSM57TMKANA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-08-26 08:29 UTC, Birdulon requested changes

2022-08-26 08:29 UTC, Birdulon commented on src/main/java/emu/grasscutter/auth/DefaultAuthenticators.java
> +                    response.message = translate("messages.dispatch.account.password_error");
```suggestion
                    response.message = translate("messages.dispatch.account.password_error");
                    return response;
```

2022-08-26 08:52 UTC, Birdulon commented
There's still a fair bit of duplication between `PasswordAuthenticator` and `ExperimentalPasswordAuthenticator`, it might be best to restructure `PasswordAuthenticator` to handle most of the steps in a new method, have `ExperimentalPasswordAuthenticator` inherit `PasswordAuthenticator` and just override a new method which does the actual password checking.

2022-08-26 12:48 UTC, jianxingxuejian commented
yes, there is still a lot of room for optimizatio

2022-08-27 11:49 UTC, Birdulon commented
> I merge into one class, will it cause harm in the future?

Plugins like to subclass/override the authenticators. I'd suggest leaving them in separate classes, but have `ExperimentalPasswordAuthenticator` subclass `PasswordAuthenticator`.

2022-09-11 15:21 UTC, KingRainbow44 requested changes

2022-09-11 15:21 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/http/objects/AuthenticateResponse.java
> +public class AuthenticateResponse {
small pet peeve: please rename to `AuthenticationResponse`

2022-10-24 15:48 UTC, closed without merging