Console output player command
Melledy/Grasscutter pull request #1722
Opened 2022-08-29 01:59 UTC by Kawaa-qwq

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR

Implement the console output player command

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2022-08-29 17:10 UTC, 2y8e9h22 commented
这啥啊，请关闭这个pr。

2022-08-30 04:53 UTC, Kawaa-qwq commented
> 这啥啊，请关闭这个pr。

我觉得只pr readme的人并没有权利教我做事

2022-08-30 08:48 UTC, Birdulon requested changes

2022-08-30 08:48 UTC, Birdulon commented on src/main/java/emu/grasscutter/command/CommandMap.java
> +    public static emu.grasscutter.command.CommandMap getInstance() {
?

2022-08-30 08:48 UTC, Birdulon commented on src/main/java/emu/grasscutter/command/CommandMap.java
> +    public emu.grasscutter.command.CommandMap registerCommand(String label, CommandHandler command) {
?

2022-08-30 08:48 UTC, Birdulon commented on src/main/java/emu/grasscutter/command/CommandMap.java
> +    public emu.grasscutter.command.CommandMap unregisterCommand(String label) {
?

2022-08-30 08:48 UTC, Birdulon commented on src/main/java/emu/grasscutter/command/CommandMap.java
> +        String message = "";
unused variable

2022-08-30 08:54 UTC, Birdulon commented
Context for anyone else viewing this: it appears to be another edition of #1019 (related issues #981 #1043)
It logs all command usage, which was previously recommended to just leave as an addon last time the topic was brought up. I've reviewed purely on code style (i.e. please don't change method names to fully-qualified names without reason, please don't introduce unused variables), but I'll leave it up to @Melledy and/or @KingRainbow44 to decide if it should actually be merged after those are fixed.

2022-08-30 09:27 UTC, Melledy commented
Please make the changes @Birdulon requested and make a config option to control player command logging. Thank you.

2022-08-30 09:35 UTC, ChisatoNishikigi73 commented
> Please make the changes @Birdulon requested and make a config option to control player command logging. Thank you.

OK,i will

2022-08-30 10:18 UTC, Kawaa-qwq commented
I changed it

2022-08-31 10:27 UTC, Melledy approved these changes

2022-08-31 10:31 UTC, Birdulon approved these changes

2022-08-31 10:40 UTC, merged