Improve team respawn
Melledy/Grasscutter pull request #1752
Opened 2022-09-06 12:20 UTC by Kawaa-qwq

## Description
Improved the squad resurrection system so that a player's entire squad is resurrected at the nearest point after death.

## TODO
- [ ] Big world 
- [ ] Dungeon 

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2022-09-09 13:05 UTC, Kawaa-qwq commented
@Birdulon I wonder if there are any suggestions for loading scenarios? After each resurrection, the entity will fall because it is not refreshed

2022-09-11 12:46 UTC, GanyusLeftHorn requested changes

2022-09-11 12:46 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/player/TeamManager.java
> +    }
This already exists, in `Utils::getDist`.

2022-09-11 12:46 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/player/TeamManager.java
> +    }
I haven't tested this, but it seems to me like this whole method could be replaced by the much more concise:

```java
public Position getRespawnPosition() {
    var deathPos = this.getPlayer().getPosition();
    int sceneId = this.getPlayer().getSceneId();

    // Get closest trans point to where the player died.
    var respawnPoint = GameData.getScenePointsPerScene().get(sceneId).stream()
        .map(pointId -> GameData.getScenePointEntryById(sceneId, pointId))
        .filter(point -> point.getPointData().getType().equals("SceneTransPoint"))
        .min(((pos1, pos2) -> Double.compare(Utils.getDist(pos1.getPointData().getTranPos(), deathPos), Utils.getDist(pos2.getPointData().getTranPos(), deathPos))));

    return respawnPoint.get().getPointData().getTranPos();
}
```

That would also solve the problem of non-`SceneTransPoint` points in scenes other than `3`, which are currently not handled by your implementation.

2022-09-11 14:09 UTC, GanyusLeftHorn approved these changes
Looks good to me.

2022-09-11 14:14 UTC, GanyusLeftHorn commented
Now that I think about it, maybe we want to make sure to only teleport the player to a trans point they actually have unlocked? If so, simply changing

```java
var respawnPoint = GameData.getScenePointsPerScene().get(sceneId).stream()
```

to

```java
var respawnPoint = this.getPlayer().getUnlockedScenePoints(sceneId).stream()
```

should do the trick.

2022-09-11 15:18 UTC, KingRainbow44 requested changes, later dismissed

2022-09-11 15:18 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/game/player/TeamManager.java
> +        var respawnPoint = GameData.getScenePointsPerScene().get(sceneId).stream()
Please apply @GanyusLeftHorn's changes. (get player's unlocked waypoints)

2022-09-12 11:36 UTC, ChisatoNishikigi73 commented on src/main/java/emu/grasscutter/game/player/TeamManager.java
> +    }
Should this be here?

2022-09-12 11:36 UTC, ChisatoNishikigi73 commented on src/main/java/emu/grasscutter/game/player/TeamManager.java
> +    }
.min(((pos1, pos2) -> Double.compare(Utils.getDist(pos1.getPointData().getTranPos(), deathPos), Utils.getDist(pos2.getPointData().getTranPos(), deathPos))));
-->>
.min((Comparator.comparingDouble(pos -> Utils.getDist(pos.getPointData().getTranPos(), deathPos))));

it's ok?

2022-09-12 11:36 UTC, ChisatoNishikigi73 commented on src/main/java/emu/grasscutter/game/player/TeamManager.java
> +    }
Yes, I completely forgot about it and wrote a method myself

2022-09-12 11:40 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/player/TeamManager.java
> +    }
> it's ok?

Yes, that should work fine.

2022-09-12 12:42 UTC, memetrollsXD approved these changes

2022-09-12 13:07 UTC, Kawaa-qwq commented
It's possible that the player hasn't opened any points,
It ensures that the player has no place to respawn.

`try{
            this.getPlayer().sendPacket(new PacketPlayerEnterSceneNotify(this.getPlayer(), EnterType.ENTER_TYPE_SELF, EnterReason.Revival, player.getSceneId(), getRespawnPosition()));
            player.getPosition().set(getRespawnPosition());
        }catch(Exception e){
            this.getPlayer().sendPacket(new PacketPlayerEnterSceneNotify(this.getPlayer(), EnterType.ENTER_TYPE_SELF, EnterReason.Revival, 3, GameConstants.START_POSITION));
            player.getPosition().set(GameConstants.START_POSITION);  // If something goes wrong, the resurrection is here
        }`

2022-09-12 13:27 UTC, GanyusLeftHorn approved these changes

2022-09-12 13:52 UTC, Birdulon approved these changes
Seems fine for overworld.

Domain wipes seem broken regardless, can't respawn/retry, exit button doesn't exit, manually exiting brings you to overworld with dead team, then relogging brings them all to 100% hp. Something to tackle later.

2022-09-12 13:52 UTC, Birdulon commented on src/main/java/emu/grasscutter/game/player/TeamManager.java
> +import emu.grasscutter.data.binout.ScenePointEntry;
```suggestion
```

unused import

2022-09-12 13:55 UTC, merged

2022-09-13 03:18 UTC, Kawaa-qwq commented
> Seems fine for overworld.
> 
> Domain wipes seem broken regardless, can't respawn/retry, exit button doesn't exit, manually exiting brings you to overworld with dead team, then relogging brings them all to 100% hp. Something to tackle later.

Yes, I noticed from the beginning, I am going to pull a new PR to fix all the Dungeon issues, but I don't know if this has happened before because I noticed that there is no code for the 3 buttons.