add SwitchElement command
Melledy/Grasscutter pull request #1819
Opened 2022-10-02 08:30 UTC by TomyJan

## Description

Switching the traveler's element. 
Although a [similar PR](https://github.com/Grasscutters/Grasscutter/pull/1287) has been turned off, I think this command is still necessary, because most of the actions in the game can be done with commands at the moment, and this should not be an exception. 
The code was modified from the source code of a plugin from an unknown source in the community, so I can't credit the original contributor. 

## Type of changes

- [ ] Bug fix
- [x] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2022-10-02 09:53 UTC, Bannyfelt13 commented
i guess maybe just use plugin

2022-10-02 10:01 UTC, tamilpp25 requested changes

2022-10-02 10:01 UTC, tamilpp25 commented on src/main/java/emu/grasscutter/command/commands/SwitchElementCommand.java
> +    private static Method getPositionMethod() {
why version support? this isn't a plugin now right?

2022-10-02 10:06 UTC, closed without merging

2022-10-20 05:53 UTC, Penelopeep commented
Yes, I see it's being marked as closed but let me say two things:
1. I'm the author of this plugin, and this one is a very old version.
2. I'm still up to adding it as Grasscutter command but this one and the old or was closed "in favor of this plugin" so if you want to add this properly then let me know, I'll help you with this spaghetti code