Update SpawnCommand.java
Melledy/Grasscutter pull request #1840
Opened 2022-10-07 23:16 UTC by NickTheHuy

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2022-10-07 23:37 UTC, Hartie95 commented
Why do you want to remove the drop alias and why won't you remove the alias line completely and instead set the command itself as alias?

2022-10-07 23:46 UTC, NickTheHuy commented
> Why do you want to remove the drop alias and why won't you remove the alias line completely and instead set the command itself as alias?

well its spawn command not drop command. i saw a lot of people struggling to spawn enemies because instead of /spawn <enemyid> it became something like /drop <enemyid> which is kinda stupid for a spawn command

2022-10-07 23:47 UTC, NickTheHuy commented
also its a very simple and quick fix. let's say that the problem was fixed, wasn't it?

2022-10-07 23:53 UTC, Hartie95 commented
> > Why do you want to remove the drop alias and why won't you remove the alias line completely and instead set the command itself as alias?
> 
> well its spawn command not drop command. i saw a lot of people struggling to spawn enemies because instead of /spawn it became something like /drop which is kinda stupid for a spawn command

But both work, and it can also be used to create drops and gadgets, in which case drop makes sense.
Also if you would remove the alias, it would one, not be bugfix, and two, you would remove the complete alias line, not replace it with what the command already is, since the command itself is not an alias.

2022-10-08 00:01 UTC, Hartie95 commented
Instead of removing drop, you could add a shorter alias, that makes sence and is less confusing, since the help description always uses the shortest alias.
Maybe something like `spn` or `sp` as alias would be less confusing.

2022-10-08 00:04 UTC, NickTheHuy commented
ok now its enough? XD

2022-10-08 00:20 UTC, Hartie95 commented
> ok now its enough? XD

Besides the info about either removing it fully, or adding another one, it was all suggestions from my side. And in the end the grasscuter team decides what gets merged, not me. 
Also if you add an alias thats shorter then drop, there is no need to also remove drop, you could have both aliases. ^^

2022-10-08 00:56 UTC, Birdulon commented
> i saw a lot of people struggling to spawn enemies because instead of /spawn it became something like /drop which is kinda stupid for a spawn command

It's not though?
![image](https://user-images.githubusercontent.com/5397662/194679361-84e874c8-af34-4659-99aa-79c6c5a5bb89.png)
![image](https://user-images.githubusercontent.com/5397662/194679403-52dc2a9b-90d2-4ff9-bf17-255d11fcbb43.png)

As Hartie pointed out, it's still very much "drop" in the context of items. It could probably have `s` as an alias but I see no reason to remove the `drop` alias.

2022-10-09 00:36 UTC, Birdulon requested changes

2022-10-09 00:36 UTC, Birdulon commented on src/main/java/emu/grasscutter/command/commands/SpawnCommand.java
> +    aliases = {"spn"},
```suggestion
    aliases = {"s", "drop"},
```

2022-10-24 00:02 UTC, closed without merging