Update README.md
Melledy/Grasscutter pull request #192
Opened 2022-04-24 13:59 UTC by Wansn-w

- Adds badge.
- Beautification. 
- Optimize Quick setup. 
- Use table to list commands. 
- add Linux compilation guide.

2022-04-24 14:14 UTC, Melledy requested changes
Looks great, but java 16 is now required on the development branch. Also, please put the building section a little higher in the readme (preferbably above the commands section)

2022-04-24 14:19 UTC, lunaticwhat commented
nice work ! 
but development branch required different java development kit version and also have some different information. You can commit your edit later after @Melledy approved my commit #181

2022-04-24 14:28 UTC, Wansn-w commented
> Looks great, but java 16 is now required on the development branch. Also, please put the building section a little higher in the readme (preferbably above the commands section)

Modified

2022-04-24 14:41 UTC, lunaticwhat requested changes

2022-04-24 14:41 UTC, lunaticwhat commented on README.md
>  **you can also use `run.cmd` to start servers and proxy daemons automatically**
actually changed into start.cmd now

2022-04-24 15:00 UTC, Wansn-w commented
I want to solve the conflict, but I've turned off the computer, so it's difficult to solve the conflict😢

2022-04-24 17:37 UTC, GoldElysium commented
Hmm, maybe add another link to the wiki troubleshooting guide in the Quick Troubleshooting section?

2022-04-24 17:39 UTC, Wansn-w commented
> Hmm, maybe add another link to the wiki troubleshooting guide in the Quick Troubleshooting section? 

That makes sense.... Btw I think it seems that the command should also be moved there, although I can't edit the wiki

2022-04-24 17:43 UTC, GoldElysium commented
> > Hmm, maybe add another link to the wiki troubleshooting guide in the Quick Troubleshooting section?
> 
> That makes sense.... Btw I think it seems that the command should also be moved there, although I can't edit the wiki

Yup. Would make sense, would have to ask a maintainer to do that.

2022-04-24 18:55 UTC, lunaticwhat commented
> I want to solve the conflict, but I've turned off the computer, so it's difficult to solve the conflict😢

uhh sometime just remove your fork and re-fork after that do the commit again xD easy way to solve conflicting

2022-04-25 02:26 UTC, Wansn-w commented
> > I want to solve the conflict, but I've turned off the computer, so it's difficult to solve the conflict😢
> 
> uhh sometime just remove your fork and re-fork after that do the commit again xD easy way to solve conflicting 

i think so XD

2022-04-25 02:34 UTC, closed without merging