Update Banners.json
Melledy/Grasscutter pull request #1932
Opened 2022-11-04 05:15 UTC by Poempoat

3.2 Banners

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2022-11-04 05:24 UTC, Birdulon commented
This diff is unusable. It deletes Beginner's Banner, Character Event Banner 1, Character Event Banner 2 and Weapon Event banner, and inserts new Character Event and Weapon banners at the start of the file with some deprecated fields and some fields which literally don't exist.
Please use the existing file as a starting point and make the minimum required changes (i.e. `prefabPath`, `titlePath`, `rateUpItems5` and `rateUpItems4` for Character Event Banners 1&2 and Weapon Event Banner)

2022-11-04 13:45 UTC, YinCQL commented
你的第二次提交仍有一点问题 (有个地方代码重复了...) ，你应该在原文件的基础上对于每个卡池仅修改这四个  “prefabPath” “titlePath” “rateUpItems4” “rateUpItems5” . 其他的保持不变。

2022-11-05 03:05 UTC, Birdulon requested changes
I'm sorry but I can't understand where you are coming from at this point and I might just update the file myself.

2022-11-05 03:05 UTC, Birdulon commented on src/main/resources/defaults/data/Banners.json
> +		"rateUpItems2": [1073]
`rateUpItems1` and `rateUpItems2` were deprecated 6 months ago. Additionally, you've set the featured 4-star pool to be the banner 5-star?

2022-11-05 03:05 UTC, Birdulon commented on src/main/resources/defaults/data/Banners.json
> +		"weights5":[[1,75],[73,150],[90,10000]],
Why are you deleting `Character Event Banner 2` and changing the weights to match Standard?

2022-11-05 03:05 UTC, Birdulon commented on src/main/resources/defaults/data/Banners.json
> +		"rateUpItems4": [14511]
Why are you setting the 4-star pool to one of the two featured 5-stars?

2022-11-05 03:05 UTC, Birdulon commented on src/main/resources/defaults/data/Banners.json
> +		"weights5":[[1,10000],[73,10000],[90,10000]],
Why are you changing the weights? Why hard pity at 73? Why an additional curve point at 90 when 10000 has already been placed?

2022-11-05 03:27 UTC, closed without merging