Added EntitySpawnEvent
Melledy/Grasscutter pull request #2007
Opened 2023-01-02 19:02 UTC by PengLx

## Description
EntitySpawnEvent add.
It will help plugin developer modify the mob or item and other entity when it spawn.

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2023-01-04 23:04 UTC, GanyusLeftHorn requested changes

2023-01-04 23:04 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/world/Scene.java
> +
Please remove empty line.

2023-01-04 23:04 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/world/Scene.java
> +
Please remove empty line.

2023-01-04 23:04 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/world/Scene.java
Please remove empty line.

2023-01-04 23:04 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/world/Scene.java
> +
Please remove empty line.

2023-01-04 23:04 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/world/Scene.java
> +            if(event.isCanceled()) continue;
This will not correctly cancel. The packet sent in line 256 will still contain all entities passed to the method, even those that were cancelled.

2023-01-13 14:26 UTC, PengLx commented
Ok I will resolve it.

2023-01-13 17:21 UTC, KingRainbow44 requested changes

2023-01-13 17:21 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/event/entity/EntitySpawnEvent.java
> +    public EntitySpawnEvent(GameEntity entity, @Nullable Player player) {
Please document the `player` field.

2023-01-14 02:19 UTC, GanyusLeftHorn requested changes

2023-01-14 02:19 UTC, GanyusLeftHorn commented on src/main/java/emu/grasscutter/game/world/Scene.java
> +                entities.remove(entity);
This does not work. You are not allowed to modify a collection directly while iterating over it. You will get a `ConcurrentModificationException`. To do this in the way you planned, you have to remove the item via the iterator, which you don't have access to when using a range-based for loop. So, either you use explicit iterators, or you create a new list with the retained items.

2023-02-22 01:01 UTC, KingRainbow44 commented
closing due to inactivity; feel free to reopen/create a new PR with the requested changes if you wish

2023-02-22 01:01 UTC, closed without merging