Some fix about scene script and quest
Melledy/Grasscutter pull request #2029
Opened 2023-01-26 15:23 UTC by ZanyRain

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
- [ScriptLib] Query player when not get entity from scene
Q351 will use the ScriptLib.GetEntityType as finish condition
The script will put userId and want to get **EntityType.Avatar** as result
And TODO maybe account id length should be limit as the official to 9 to avoid conflict other entity id.
- Fix NPE when doing quests
- Add QUEST_CONTENT_SKILL trigger
Q352 need it.
- Add a lua table serializer implement with jackson
This is not going to replace the default one, but provide an alternative. 
When using the default one, it throws some exceptions, but I can not figure out why
````
> java.lang.RuntimeException: Class cannot be created (missing no-arg constructor): sun.reflect.generics.reflectiveObjects.TypeVariableImpl
	at com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:68)
	at emu.grasscutter.scripts.serializer.LuaSerializer.cacheType(LuaSerializer.java:191)
	at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:139)
	at emu.grasscutter.scripts.serializer.LuaSerializer.serializeList(LuaSerializer.java:97)
	at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:130)
	at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:161)
	at emu.grasscutter.scripts.serializer.LuaSerializer.serializeMap(LuaSerializer.java:54)
	at emu.grasscutter.scripts.serializer.LuaSerializer.toMap(LuaSerializer.java:35)
	at emu.grasscutter.game.quest.GameMainQuest.addRewindPoints(GameMainQuest.java:208)
	at emu.grasscutter.game.quest.GameMainQuest.<init>(GameMainQuest.java:79)
	at emu.grasscutter.game.quest.QuestManager.addMainQuest(QuestManager.java:178)
	at emu.grasscutter.game.quest.QuestManager.addQuest(QuestManager.java:197)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at emu.grasscutter.game.quest.QuestManager.startMainQuest(QuestManager.java:226)
	at java.base/java.util.Spliterators$IntArraySpliterator.forEachRemaining(Spliterators.java:1076)
	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
	at emu.grasscutter.game.quest.GameMainQuest.finish(GameMainQuest.java:150)
	at emu.grasscutter.game.quest.GameQuest.finish(GameQuest.java:142)
	at emu.grasscutter.game.quest.GameMainQuest.tryFinishSubQuests(GameMainQuest.java:337)
	at emu.grasscutter.game.quest.QuestManager.triggerEvent(QuestManager.java:276)
	at emu.grasscutter.game.quest.QuestManager.triggerEvent(QuestManager.java:229)
	at emu.grasscutter.server.packet.recv.HandlerAddQuestContentProgressReq.handle(HandlerAddQuestContentProgressReq.java:29)
	at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:93)
	at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:222)
	at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchMethodException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
	at com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:65)
	... 30 more
````
, so I reimplement one using jackson, it works well.
And the scene script is ugly, difficult to read, make lua table to json and then to Java object can help to log the script data 
- Add some missing fields that contain in scene scripts
This is the jackson serializer above helps me

**Happy Lantern Rite and Spring Festival**
## Issues fixed by this PR

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2023-01-26 16:45 UTC, Hartie95 commented
If you are interested in quests, I can recommend taking a look at my fork, where we are working on getting most of the quest framework running.

https://github.com/Anime-Game-Servers/Grasscutter-Quests

We are planing to bring the improvements back into the main project in the end, but many parts need/needed refactoring for it to fully work.
Currently quests from 351 to the 3 dungeons work without any command, then you need a command to enter the dungeons.
All dungeons can now be completed more or less without commands, and afterwards auto progression fails, but a big part of the gliding challenge also works.
StartForKiller also recently Chelanged group loafing to be more like on official, so now less random monster will be there.
I'm also currently testing a different handling for accept conditions, that allows hidden and side quests to automatically trigger.

2023-01-27 03:44 UTC, ZanyRain commented
> If you are interested in quests, I can recommend taking a look at my fork, where we are working on getting most of the quest framework running.
> 
> https://github.com/Anime-Game-Servers/Grasscutter-Quests
> 
> We are planing to bring the improvements back into the main project in the end, but many parts need/needed refactoring for it to fully work. Currently quests from 351 to the 3 dungeons work without any command, then you need a command to enter the dungeons. All dungeons can now be completed more or less without commands, and afterwards auto progression fails, but a big part of the gliding challenge also works. StartForKiller also recently changed group loading to be more like on official, so now less random monster will be there. I'm also currently testing a different handling for accept conditions, that allows hidden and side quests to automatically trigger.

Good work

2023-01-29 20:18 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/scripts/SceneScriptManager.java
> +        }
New line here please.

2023-01-29 20:20 UTC, KingRainbow44 requested changes, later dismissed

2023-01-29 20:20 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/scripts/serializer/LuaTableJacksonSerializer.java
> +            }
Please fix your spacing. (`} else if (`)

2023-01-29 20:20 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/scripts/serializer/LuaTableJacksonSerializer.java
> +            }
Please fix your spacing. (see above)

2023-01-29 20:20 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/scripts/serializer/LuaTableJacksonSerializer.java
> +        Grasscutter.getLogger().trace("[LuaTableToList] className={},data={}",type.getCanonicalName(),jsonNode.toString());
Please fix your spacing. (`, `)

2023-01-29 20:20 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/scripts/serializer/LuaTableJacksonSerializer.java
> +        }else if (jsonNode.isObject()) {
spacing

2023-01-29 20:20 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/scripts/serializer/LuaTableJacksonSerializer.java
> +        Grasscutter.getLogger().trace("[LuaTableToObject] className={},data={}",type.getCanonicalName(),jsonNode.toString());
spacing

2023-01-29 20:20 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/scripts/serializer/LuaTableJacksonSerializer.java
> +        Grasscutter.getLogger().trace("[LuaTableToMap] className={},data={}",type.getCanonicalName(),jsonNode.toString());
spacing

2023-01-29 20:20 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/packet/recv/HandlerEvtDoSkillSuccNotify.java
> +        player.getQuestManager().triggerEvent(QuestTrigger.QUEST_CONTENT_SKILL,skillId,0);
spacing

2023-02-09 16:08 UTC, GanyusLeftHorn approved these changes

2023-02-09 16:10 UTC, merged