CNREL support
Melledy/Grasscutter pull request #2076
Opened 2023-03-10 12:19 UTC by rwx9032

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR
Fix CNREL client can't be played

Special thanks to @xlpmyxhdr 

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2023-03-10 16:34 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/http/dispatch/DispatchHandler.java
> +}
Please leave the new line at the end of the file.

2023-03-10 16:37 UTC, KingRainbow44 requested changes
Consider removing the `messages.status.versionos` key from the languages file. As the message is more of a 'debug message' instead of a critical message for the server administrator, it makes more sense to keep this message hardcoded in existing places. (and to switch the log level for these messages from `info` to `debug`)

2023-03-10 16:37 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/http/dispatch/DispatchHandler.java
> +            .authenticate(AuthenticationSystem.fromComboTokenRequest(ctx, bodyData, tokenData));
Maintain spacing.

2023-03-10 16:37 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/http/dispatch/DispatchHandler.java
> +            .authenticate(AuthenticationSystem.fromTokenRequest(ctx, bodyData));
Maintain spacing.

2023-03-10 16:37 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/http/dispatch/DispatchHandler.java
> +            .authenticate(AuthenticationSystem.fromPasswordRequest(ctx, bodyData));
Maintain spacing.

2023-03-10 16:37 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/http/dispatch/DispatchHandler.java
> +            .handleRedirection(AuthenticationSystem.fromExternalRequest(ctx), ClientType.MOBILE));
Maintain spacing.

2023-03-10 16:37 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/http/dispatch/RegionHandler.java
> +                logger.info(translate("messages.status.versioncn"));
```suggestion
                logger.debug(translate("messages.status.versioncn"));
```

2023-03-10 16:37 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/http/dispatch/RegionHandler.java
> +                logger.info(translate("messages.status.versionos"));
```suggestion
                logger.debug(translate("messages.status.versionos"));
```

2023-03-10 16:37 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/http/dispatch/RegionHandler.java
> +                logger.info(translate("messages.status.versionos"));
```suggestion
                logger.debug(translate("messages.status.versionos"));
```

2023-03-10 16:37 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/http/dispatch/RegionHandler.java
> +            logger.info(translate("messages.status.versionos"));
```suggestion
            logger.debug(translate("messages.status.versionos"));
```

2023-03-10 17:19 UTC, rwx9032 commented
Already deleted the language keys and hardcoded the debug output

2023-03-11 00:43 UTC, KingRainbow44 approved these changes

2023-03-11 00:44 UTC, KingRainbow44 commented
can you/someone else test it and send a video of it working here? (with debug logs on preferably)

2023-03-11 06:56 UTC, rwx9032 commented
https://user-images.githubusercontent.com/61132134/224469969-5c9a46e4-c08c-443f-9a56-ad888f8887b1.mp4

2023-03-11 22:07 UTC, thecutefinder approved these changes
Looks good

2023-03-12 05:51 UTC, merged