Pr new drop
Melledy/Grasscutter pull request #2112
Opened 2023-04-13 05:16 UTC by eternalcomet

## Description
Implment a new drop system,including chest rewards, boss chest rewards, monster drop, investigation points, BGM CDs collection,etc.
I renamed old DropSystem to DropSystemLegacy, if new drop system failed to find necessary resources it will fallback to the legacy one.

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.

## Issues fixed by this PR

## Type of changes

- [ ] Bug fix
- [x] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2023-04-13 05:20 UTC, eternalcomet commented
Maybe need to clean lombok annotations in GameData.java, @KingRainbow44 you can do it since i'm not familiar with that.

2023-04-13 05:21 UTC, KingRainbow44 requested changes
please replace `onMethod = @__(@Override)` with the JDK 8 version which uses `onMethod_ = @Override`

2023-04-13 05:22 UTC, KingRainbow44 commented
additionally, run `./gradlew spotlessFormat` to format your code!

2023-04-13 05:26 UTC, eternalcomet commented
I'll do it later.

2023-04-13 19:35 UTC, KingRainbow44 requested changes

2023-04-13 19:35 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/command/commands/ReloadCommand.java
> +        Grasscutter.getGameServer().getDropSystemLegacy().load();
Please reload the new drop system, or remove the existing drop system from the reload command.

2023-04-13 19:35 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/data/GameData.java
> +    @Getter private static final Int2ObjectMap<DropMaterialData> dropMaterialDataMap=new Int2ObjectOpenHashMap<>();
```suggestion
    @Getter private static final Int2ObjectMap<DropTableData> dropTableDataMa p= new Int2ObjectOpenHashMap<>();
    @Getter private static final Int2ObjectMap<DropMaterialData> dropMaterialDataMap = new Int2ObjectOpenHashMap<>();
```

2023-04-13 19:35 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/data/excels/DropMaterialData.java
> +    @Getter(onMethod = @__(@Override))
```suggestion
    @Getter(onMethod_ = @Override)
```

2023-04-13 19:35 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/data/excels/DropTableData.java
> +    @Getter(onMethod = @__(@Override))
```suggestion
    @Getter(onMethod_ = @Override)
```

2023-04-13 19:41 UTC, KingRainbow44 requested changes
Please run `./gradlew spotlessApply`

2023-04-13 19:41 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/scripts/data/SceneMonster.java
> +	public int config_id;
```suggestion
    public int config_id;
```

2023-04-13 19:41 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/scripts/data/SceneMonster.java
> +	public int pose_id;
```suggestion
    public int pose_id;
```

2023-04-13 19:41 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/scripts/data/SceneMonster.java
> +	public boolean disableWander;
```suggestion
    public int drop_id;
    public boolean disableWander;
```

2023-04-14 00:50 UTC, eternalcomet commented
> Please run `./gradlew spotlessApply`

done

2023-04-14 01:17 UTC, eternalcomet commented
I have a issue with .gitattribute file. when i checkout, i will see a tons of changes for crlf or lf, no matter what core.autocrlf is set. so maybe you can run spotlessApply yourself. sorry for that

2023-04-14 02:27 UTC, KingRainbow44 approved these changes

2023-04-14 02:28 UTC, merged