Gm handbook lmao
Melledy/Grasscutter pull request #2149
Opened 2023-05-13 06:29 UTC by Arikatsu

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.

## Issues fixed by this PR

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2023-05-13 17:56 UTC, KingRainbow44 requested changes
also run spotless apply

2023-05-13 17:56 UTC, KingRainbow44 commented on src/handbook/src/ui/components/VirtualizedGrid.tsx
> +            console.log(window.innerWidth)
```suggestion
```

2023-05-14 04:56 UTC, KingRainbow44 requested changes
address changes sent via discord. changes include:
- removing random white box on home screen
- fixing text scaling on item and entity names
- fixing the position of the scroll bar to not cut it off
- fixing text scaling on home page text, 'achievements' gets cut off
- add purple hover effect on discord community
- remove scroll bars present due to small height on command/card text boxes
- import font and icons via react, these need to be seen at compile time

2023-05-14 04:57 UTC, KingRainbow44 commented
![image](https://github.com/Grasscutters/Grasscutter/assets/27646710/6847620b-837e-4e77-a196-989b857b3a91)
![image](https://github.com/Grasscutters/Grasscutter/assets/27646710/2bd65d44-fd36-4f36-8a6b-97e6da35d457)
![image](https://github.com/Grasscutters/Grasscutter/assets/27646710/fc96e3b2-a89e-4ae3-b142-9d117529ee84)
![image](https://github.com/Grasscutters/Grasscutter/assets/27646710/809d74e7-56d0-43c3-80d1-f79626175dd8)
![image](https://github.com/Grasscutters/Grasscutter/assets/27646710/0adfcd6b-9848-4fac-bed1-8bec4bfc736c)
![image](https://github.com/Grasscutters/Grasscutter/assets/27646710/93271705-b942-41c9-81ce-81de8e262f80)

2023-05-14 07:41 UTC, lilmayofuksu commented
goobers

2023-05-14 14:12 UTC, KiminaNatsuki commented
![image](https://github.com/Grasscutters/Grasscutter/assets/34180607/d7e74966-44a0-4245-8893-2ec0b300d1fb)

2023-05-14 19:36 UTC, Arikatsu commented
goobers

2023-05-14 21:24 UTC, Arikatsu commented
this pr is so cursed 💀

2023-05-15 05:28 UTC, KingRainbow44 requested changes
fix your entity icon

2023-05-15 07:55 UTC, KingRainbow44 approved these changes

2023-05-15 07:55 UTC, merged