Fix lock clock
Melledy/Grasscutter pull request #2201
Opened 2023-06-09 11:48 UTC by scooterboo

## Description
Ignores ClientLockGameTimeNotify so that lock time works correctly. Polls PROP_IS_GAME_TIME_LOCKED at login to find out if you are in the middle of a quest with time locking. Much thanks to @LloydTheGreenNinjagc and @Hartie95 

Ya, I can't make heads or tails of what ClientLockGameTimeNotify does except it always is sending a false.

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2023-06-09 17:30 UTC, KingRainbow44 requested changes

2023-06-09 17:30 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/game/world/World.java
> +        timeLocked = player.getProperty(PlayerProperty.PROP_IS_GAME_TIME_LOCKED) != 0;
```suggestion
        this.timeLocked = player.getProperty(PlayerProperty.PROP_IS_GAME_TIME_LOCKED) != 0;
```

2023-06-09 17:30 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/packet/recv/HandlerClientLockGameTimeNotify.java
> +        //TODO: figure out what to implement here
```suggestion
        // session.getPlayer().getWorld().lockTime(packet.getIsLock());
        // TODO: figure out what to implement here
```

2023-06-09 17:30 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/server/packet/recv/HandlerClientLockGameTimeNotify.java
> +        if (packet.getIsLock()) Grasscutter.getLogger().warn("Tell Nazrin to PANIK because ClientLockGameTimeNotify is TRUE!");
```suggestion
        if (packet.getIsLock()) Grasscutter.getLogger().warn("Invalid 'ClientLockGameTimeNotify' received; value is true. (please report to development channel)");
```
consider changing to something more reasonable, example shown above

2023-06-09 19:52 UTC, scooterboo reviewed
Yep

2023-06-09 20:26 UTC, scooterboo reviewed
test

2023-06-11 03:32 UTC, KingRainbow44 approved these changes

2023-06-11 03:32 UTC, merged