fix giveall doesn't give everything
Melledy/Grasscutter pull request #2210
Opened 2023-06-14 13:03 UTC by pfyy

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.

## Issues fixed by this PR

a simple fix that makes giveall give everything again by catching the exception manually

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2023-06-14 17:52 UTC, KingRainbow44 requested changes
please change the ‘printStackTrace’ calls to debug calls to Grasscutter’s logger.

2023-06-14 18:55 UTC, pfyy commented
sorry, i was just following the original logging style of that file

2023-06-15 23:12 UTC, KingRainbow44 requested changes
please change the logger calls to `debug`, forgot to mention in the first comment sorry

2023-06-16 18:05 UTC, KingRainbow44 approved these changes

2023-06-16 18:05 UTC, KingRainbow44 approved these changes

2023-06-16 18:05 UTC, merged