Configuration Update - Shown Email
Melledy/Grasscutter pull request #2509
Opened 2024-05-05 23:10 UTC by KittenPixel-cell

This version will allow the private server owner to show a different email then "@grasscutter.io" if they want.

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.

## Issues fixed by this PR

## No fixes.

- [ ] Bug fix
- [ x ] New feature 
- [ x ] Enhancement
- [ ] Documentation

## Checklist:

- [ x ] My code follows the style guidelines of this project
- [ x ] My pull request is unique and no other pull requests have been opened for these changes
- [ x ] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [ x ] I am responsible for any copyright issues with my code if it occurs in the future.

2024-05-06 03:39 UTC, KingRainbow44 requested changes

2024-05-06 03:39 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/game/Account.java
> +        // Set account default language as fserver default language
```suggestion
        // Set account default language to server default language
```

2024-05-06 03:39 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/game/Account.java
> +            return this.getUsername() + "@"+ACCOUNT.playeremail;
```suggestion
            return this.getUsername() + "@" + ACCOUNT.playerEmail;
```

2024-05-06 03:39 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/config/ConfigContainer.java
> +        public String playeremail = "grasscutter.io";
```suggestion
        public String playerEmail = "grasscutter.io";
```

2024-05-06 22:18 UTC, KittenPixel-cell commented
Committed your requested changes King.

2024-05-08 21:02 UTC, KittenPixel-cell commented
So uhh anyone else gonna check it?

2024-05-14 01:58 UTC, KingRainbow44 approved these changes

2024-05-14 01:58 UTC, merged