Update README.md
Melledy/Grasscutter pull request #278
Opened 2022-04-27 02:04 UTC by BaiSugar

Update command /giveall

2022-04-27 02:12 UTC, iTruth requested changes

2022-04-27 02:12 UTC, iTruth commented on README.md
> +| giveall       | giveall <uid> <amount>                 | player.giveall      | Both side    | Gives all items.      | givea                                         |
almost all of the paramter is "optional"  
consider change <> to []

2022-04-27 02:20 UTC, iTruth approved these changes

2022-04-28 11:47 UTC, memetrollsXD approved these changes

2022-04-28 11:47 UTC, merged