Update README.md
Melledy/Grasscutter pull request #295
Opened 2022-04-27 09:38 UTC by memetrollsXD

2022-04-27 10:10 UTC, alphagocc requested changes

2022-04-27 10:10 UTC, alphagocc commented on README.md
> +* Startup sequence: Mongodb > Grasscutter > Proxy daemon (mitmdump, fiddler, etc.) > Genshin Impact Client
never mention `some anime games`

2022-04-27 10:15 UTC, alt3ri commented on README.md
> +* Startup sequence: Mongodb > Grasscutter > Proxy daemon (mitmdump, fiddler, etc.) > Genshin Impact Client
never mention `that anime game`

2022-04-27 10:32 UTC, memetrollsXD commented on README.md
> +* Startup sequence: Mongodb > Grasscutter > Proxy daemon (mitmdump, fiddler, etc.) > Genshin Impact Client
skull i forgor

2022-04-29 00:30 UTC, Yazawazi approved these changes

2022-04-29 23:43 UTC, KingRainbow44 approved these changes

2022-04-29 23:43 UTC, merged