Add custom HTTP server response files
Melledy/Grasscutter pull request #657
Opened 2022-05-08 01:19 UTC by 6ixfalls

## Description
Allows for a custom file to be used in case of a 404 error and to replace the default "Welcome to Grasscutter" message.
> Also fixed URLDecoder IntelliSense warning

## Type of changes

- [ ] Bug fix
- [X] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist

- [X] My code follows the style guidelines of this project
- [X] My pull request is unique and no other pull requests have been opened for these changes
- [X] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [X] I am responsible for any copyright issues with my code if it occurs in the future.

2022-05-10 10:42 UTC, memetrollsXD commented
For what would this be useful for?

2022-05-10 14:12 UTC, 6ixfalls commented
Adding a custom response file that doesn't show the default "Welcome" page or 404 page? Nice for customization imo

2022-05-14 15:12 UTC, 6ixfalls commented
Might be nice to consolidate all of these commits but there's so many refactors to DispatchServer

2022-05-14 15:14 UTC, KingRainbow44 commented
the pain of having to merge other dispatch conflicts into my pr
*someone help me I'm dying*

2022-05-14 15:33 UTC, KingRainbow44 requested changes

2022-05-14 15:33 UTC, KingRainbow44 commented on src/main/java/emu/grasscutter/utils/ConfigContainer.java
> +        public String WelcomeFile = "./welcome.html";
Use `lowerCamelCase` in the config file please.

2022-05-14 15:39 UTC, 4Benj commented
Due to a pending dispatch rework by @KingRainbow44, I will be closing this PR to prevent any merge conflicts. Hopefully this will be included in the rework but if not feel free to reopen this PR or open a new one
If it wasn't for my idiocy this would've been merged by now, I'm very sorry. 

Thank you for contributing to Grasscutter

2022-05-14 15:39 UTC, closed without merging