Add customizable Standard wish pools and 10-pull costs
Melledy/Grasscutter pull request #706
Opened 2022-05-08 17:05 UTC by SvardXI

## Description
Added the ability for users to change what items they want on the Standard wish for each of their banners, as well as the ability to to adjust the cost of 10-pulls for discounted banners.

Note: If the field(s) in the JSON is empty for the Standard pools, the server will still use mHY's official Standard pool. Additionally, while the cost of a 10-pull will show in the game's UI, it will only do it before making a 10-pull. The game will still check for (and consume) the adjusted cost.

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2022-05-08 18:27 UTC, SvardXI commented
Recently noticed one issue with my commit--

I used a source file that was a about a day old. As such, line 129 needs to be replaced:
	- String record = "https://"
	+ String record = "http" + (Grasscutter.getConfig().getDispatchOptions().FrontHTTPS ? "s" : "") + "://"

2022-05-08 20:16 UTC, HotaruYS requested changes

2022-05-08 20:16 UTC, HotaruYS commented on src/main/java/emu/grasscutter/game/gacha/GachaBanner.java
> +		String record = "https://"
Please do not revert made in other PRs changed arbitrarily. Ensure your fork is up-to-date or be very careful when merging conflicts.

2022-05-08 20:17 UTC, HotaruYS commented on src/main/java/emu/grasscutter/game/gacha/GachaBanner.java
> +		String record = "https://"
https://github.com/Grasscutters/Grasscutter/pull/649

2022-05-08 20:20 UTC, HotaruYS commented
Conflicts with changes in https://github.com/Grasscutters/Grasscutter/pull/639

---

>I used a source file that was a about a day old. As such, line 129 needs to be replaced:

You will need to do it yourself, otherwise someone would have to make another PR to fix it.

2022-05-13 12:44 UTC, Melledy commented
Thank you for wanting to contribute to our project, but i will be closing this PR as these changes were added in #639

2022-05-13 12:44 UTC, closed without merging