Remove the extra slash while loading resources.
Melledy/Grasscutter pull request #893
Opened 2022-05-14 21:28 UTC by line-bear

## Description
The new default config file already contains / at the end of path string, which may cause double slash while loading resources, It seems to work fine at the moment, but it is recommended to remove it to prevent unpredictable situations.

## Issues fixed by this PR

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2022-05-14 23:03 UTC, HotaruYS commented
We can not be sure that someone editing config file will remember to add `/` at the end of string.

2022-05-14 23:11 UTC, HotaruYS requested changes
Let's use proper path joining.

```java
import java.nio.file.Paths;
```

2022-05-14 23:11 UTC, HotaruYS commented on src/main/java/emu/grasscutter/Configuration.java
> +        return DATA_FOLDER + path;
```suggestion
        return Paths.get(DATA_FOLDER, path).toString();
```

2022-05-14 23:11 UTC, HotaruYS commented on src/main/java/emu/grasscutter/Configuration.java
> +        return RESOURCES_FOLDER + path;
```suggestion
        return Paths.get(RESOURCES_FOLDER, path).toString();
```

2022-05-14 23:11 UTC, HotaruYS commented on src/main/java/emu/grasscutter/Configuration.java
> +        return SCRIPTS_FOLDER + path;
```suggestion
        return Paths.get(SCRIPTS_FOLDER, path).toString();
```

2022-05-14 23:15 UTC, HotaruYS commented
You should also perform same changes in all other files where `*_FOLDER` are used. Most likely we should mark them as private and instead provide helper functions like `DATA` for all other ones that don't have one currently.

2022-05-15 07:41 UTC, line-bear reviewed
Use path join to prevent double slash

2022-05-15 10:18 UTC, line-bear commented
> You should also perform same changes in all other files where `*_FOLDER` are used. Most likely we should mark them as private and instead provide helper functions like `DATA` for all other ones that don't have one currently.

all done, have fun

2022-05-15 10:39 UTC, line-bear reviewed
Mark fields as private to prevent use *FOLDER directly

2022-05-15 12:34 UTC, HotaruYS commented on src/main/java/emu/grasscutter/utils/Crypto.java
> +		DISPATCH_KEY = FileUtils.read(KEY("/dispatchKey.bin"));
No need for slash here

2022-05-15 12:38 UTC, HotaruYS commented
Thanks. Looks good to me now.

Will most likely go around whole codebase in another PR later and see if we can refactor `Utils.toFilePath` to be a wrapper for path join instead of dumb replacing `/` with separator. I've also spotted few places that forget to use `Utils.toFilePath` so will need to handle that too.

2022-05-15 15:19 UTC, line-bear commented
> Thanks. Looks good to me now.
> 
> I'll most likely go around whole codebase in another PR later and see if we can refactor `Utils.toFilePath` to be a wrapper for path join instead of dumb replacing `/` with separator. I've also spotted few places that forget to use `Utils.toFilePath` so will need to handle that too.

Waitting for your message :)

2022-05-16 06:31 UTC, Melledy approved these changes

2022-05-16 06:32 UTC, merged